### ISSUE TITLE
Lag Issue

### ISSUE THREAD

**Issue by dpatrongomez** [helmiau/sagit-miui-oreo#1]
When I'm watching YouTube, the image freezes.
Rom: Xiaomi.eu 8.12.6
Kernel version: 4.4.166-Fluxions-v1.0

**Comment by helmiau** [comment]
thanks you for your response.. i hope this build will fix it https://github.com/helmiau/sagit-miui-oreo/releases/download/1.1/Fluxions-Sagit-v1.1.zip

**Comment by dpatrongomez** [comment]
Now the image and sound freeze with that version, for example in games doesn´t happend

**Comment by helmiau** [comment]
> Now the image and sound freeze with that version, for example in games doesn´t happend

have you a telegram? if you have telegram please chat me @helmiau
