### ISSUE TITLE
Is the happening normal?

### ISSUE THREAD

**Issue by grislux55** [helmiau/sagit-miui-oreo#3]
I didn't see these Governors :
Impulse
Alucard
Darkness

**Comment by grislux55** [comment]
Version :
1.6

**Comment by grislux55** [comment]
oh，when i switch to 1.5, i can see it!

**Comment by helmiau** [comment]
I remove them sir... Wanna get thats back?

**Comment by grislux55** [comment]
no，i found these gover such as alucard will lead to cpu locked. is it bugs? or feature?
